// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7qpdkJFudAdiJrsXCm7qY_TFCk-_inwE',
    appId: '1:798407068989:ios:b5e75a2fd2ff0dab7a8954',
    messagingSenderId: '798407068989',
    projectId: 'proyecto-pad',
    storageBucket: 'proyecto-pad.appspot.com',
    iosBundleId: 'com.example.appPadel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7qpdkJFudAdiJrsXCm7qY_TFCk-_inwE',
    appId: '1:798407068989:ios:b5e75a2fd2ff0dab7a8954',
    messagingSenderId: '798407068989',
    projectId: 'proyecto-pad',
    storageBucket: 'proyecto-pad.appspot.com',
    iosBundleId: 'com.example.appPadel',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3jT1f7qEOFcfMWzeBwiK8XTkKNcSA-pw',
    appId: '1:798407068989:web:f7dea619ca9506987a8954',
    messagingSenderId: '798407068989',
    projectId: 'proyecto-pad',
    authDomain: 'proyecto-pad.firebaseapp.com',
    storageBucket: 'proyecto-pad.appspot.com',
    measurementId: 'G-R5SNQFT3VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWdp03qD9C_IiismbQEhp6ED1hsflepRY',
    appId: '1:798407068989:android:cecf87f5369274467a8954',
    messagingSenderId: '798407068989',
    projectId: 'proyecto-pad',
    storageBucket: 'proyecto-pad.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3jT1f7qEOFcfMWzeBwiK8XTkKNcSA-pw',
    appId: '1:798407068989:web:5c8140d89fa379277a8954',
    messagingSenderId: '798407068989',
    projectId: 'proyecto-pad',
    authDomain: 'proyecto-pad.firebaseapp.com',
    storageBucket: 'proyecto-pad.appspot.com',
    measurementId: 'G-E8ESNNCD2T',
  );

}